### ISSUE TITLE
Doesn't work with the latest version of objective

### ISSUE THREAD

**Issue by gelisam** [gelisam/frp-zoo#14]
Since it's not an FRP library, I'm not terribly interested in keeping this example up-to-date, so unless @fumieval sends an updated version, I think I'm just going to hide it from the list.

**Comment by fumieval** [comment]
Sorry for not maintaining it.

I think `objective` can be thought of as a "lifted" AFRP library since the basic `Object` type is quite similar to the simple signal function:

```haskell
newtype SF a b = SF { step :: a -> (b, SF a b) }
newtype Object f g = Object { runObject :: f a -> g (a, Object f g) }
```

And actually `Object f g` can be specialized to `SF`. I'm working on a paper for this right now.

Anyway I'd be happy if you cherry-pick the patch 6f99e66.

**Comment by gelisam** [comment]
That was fast! Thanks for the patch, and I'll be looking forward to reading this paper.

When I saw your example code for objective, I thought it clearly wasn't FRP because I didn't recognize any of the primitives which I expected to be [common to all FRP libraries](https://github.com/gelisam/frp-zoo#static-implementation): filtering events, combining current values, and accumulating changes to a local state. But now that you're showing me the types, I agree that this looks a lot like the automatons of Arrowized FRP. Looking closer, I see that you've defined `fold0` for accumulating changes to a local state -- would it make sense to also define primitives for filtering and combining values? I think it might help to make your example code closer to the structure used by the other examples, which would in turn make the differences easier to spot.
