### ISSUE TITLE
add reflex

### ISSUE THREAD

**Issue by gelisam** [gelisam/frp-zoo#17]
Just heard about this new FRP library from those posts:
http://www.reddit.com/r/haskell/comments/31rat9/reflex_practical_functional_reactive_programming/
http://www.reddit.com/r/haskell/comments/31rlb4/reflex_practical_functional_reactive_programming/

It's probably this package:
https://hackage.haskell.org/package/reflex

**Comment by jeffreyrosenbluth** [comment]
I should have this done in a few days.

**Comment by gelisam** [comment]
Great, thanks!

**Comment by jeffreyrosenbluth** [comment]
I'd like to use a few features in reflex 0.3 which should come out by the end of the week, so
i'm holding off the pr until then.

**Comment by jeffreyrosenbluth** [comment]
Everything is done and ready to go, unfortunately reflex is being help up until a pr is merged into a dependency. I can submit a pr now and you can try it against the develop branch of reflex, but it wouldn't able to be merged until reflex 0.3 comes out. Alternatively, I can just wait for 0.3 before submitting a pr here.

**Comment by gelisam** [comment]
I don't mind either way.

**Comment by gelisam** [comment]
Thanks for your contribution! I gave you commit access, in case you need to make changes later or if there are other FRP implementations you'd like to add.

**Comment by jeffreyrosenbluth** [comment]
sounds good, thanks
