### ISSUE TITLE
add FRPNow

### ISSUE THREAD

**Issue by gelisam** [gelisam/frp-zoo#19]
Just released: https://www.reddit.com/r/haskell/comments/3ddn1b/announce_frpnow012/

**Comment by as-capabl** [comment]
I'd like to write an example for this library.

And I have a question.
For FRPNow, there is [an official binding of gloss](http://hackage.haskell.org/package/frpnow-gloss).
The interface looks quite similar to our GlossInterface.hs for other libraries.

Should I write new GlossInterface.hs for FRPNow, or use the offical one?

**Comment by gelisam** [comment]
> I'd like to write an example for this library.

Great! Thanks for contributing.

> Should I write new GlossInterface.hs for FRPNow, or use the offical one?

Please use the official one. I only added a `GlossInterface.hs` implementation for those FRP libraries which don't have (or for which I don't know of) a gloss interoperability layer. Which, surprisingly, is almost all of them :(

**Comment by as-capabl** [comment]
I'm not sure whether the scenario 5 can be implemented or not.
For now, close this issue.
