### ISSUE TITLE
add Francium

### ISSUE THREAD

**Issue by gelisam** [gelisam/frp-zoo#20]
https://github.com/ocharles/Francium

I see more and more FRP libraries targetted at web development. We should define a variant of the test program which uses the browser instead of gloss.

**Comment by jeffreyrosenbluth** [comment]
Francium is just a layer on top of reactive-bannana that compiles
to ghcjs and provides a dom api.

**Comment by gelisam** [comment]
Ah! Since we already have an implementation for reactive-banana, I guess there's not much benefit to provide an implementation for Francium too, then, so I'll close the issue. Thanks for letting me know!
