### ISSUE TITLE
add Auto

### ISSUE THREAD

**Issue by gelisam** [gelisam/frp-zoo#22]
http://hackage.haskell.org/package/auto

The documentation states:

> It's been called "FRP for discrete time contexts".

So I guess it belongs here as well.

**Comment by as-capabl** [comment]
This library is very close to netwire.
Possibly I can write an example by modifying netwire-example.

**Comment by gelisam** [comment]
Please do!

**Comment by as-capabl** [comment]
Sorry, wrong ticket ID. 16edb7e1eec8bc2c7da1dce7e804c3b8640a7f11

**Comment by gelisam** [comment]
I noticed you put auto in the list of non-FRP examples. From what I've been [told on reddit](https://www.reddit.com/r/haskell/comments/3f7g1m/varying_automaton_based_varying_values_event/ctmgwov?context=3), the author of auto doesn't consider auto to be FRP, but only under Conal Elliott's definition of FRP. Since most of the other FRP libraries in our list are also only considered FRP in the broader sense of the term, not Conal's, I would like to move auto from the non-FRP list to the FRP list.

Any objection?

**Comment by as-capabl** [comment]
I agree. This library can be included in FRP list.
