### ISSUE TITLE
add "step signals" label to reflex

### ISSUE THREAD

**Issue by as-capabl** [gelisam/frp-zoo#38]
It seems that the type `Dynamic` in reflex is comparable to `Discrete` types of other libraries.

**Comment by jeffreyrosenbluth** [comment]
While there are some similarities between `Dynamic` and `Discrete`, they are not the same. Reflex has a more general notion of time, i.e. time is not discrete as it is in the libraries that have "step signals". `Dynamic` is more similar to Conal's `Reactive`. I don't think "step signals" can be applied to Reflex.

**Comment by as-capabl** [comment]
Okay, I respect your opinion.
Thank you for your comment! :-)
