### ISSUE TITLE
Euphoria release on hackage

### ISSUE THREAD

**Issue by as-capabl** [gelisam/frp-zoo#40]
There's official release of euphoria.
https://hackage.haskell.org/package/euphoria

Note that it doesn't compile other than ghc-7.10
https://github.com/tsurucapital/euphoria/issues/15

**Comment by gelisam** [comment]
That version works just fine for me, and is being picked up by the existing `euphoria-example.cabal` file. Is there anything to be done, or can this issue be closed as-is?

**Comment by as-capabl** [comment]
Thank you for testing!
I'll change the link location of README.md linking to euphoria library.
