### ISSUE TITLE
sodium-example is broken

### ISSUE THREAD

**Issue by gelisam** [gelisam/frp-zoo#41]
Click 5 times on each numeric button.
Expected: 5 5 5
Actual: 5!=0 5!=0 5

Click on each toggle button.
Click 5 more times on each numeric button.
Click on each toggle button again.
Expected: 0 5 10
Actual: 0 5!=0 10

I'm certain this was working before, what changed?

By the way the "!=" indicates that the static and dynamic implementations did not match.

**Comment by the-real-blackh** [comment]
Hi - I'm the author of Sodium. For some reason in ghc-7.10.2 mkWeakIORef does not behave like it used to. I'm a bit busy but I'll get to it as soon as I can.

**Comment by gelisam** [comment]
That rings a bell. Didn't the exact same thing occur with ghc-7.8? I remember sending you a patch about a similar issue last year.

**Comment by the-real-blackh** [comment]
Yeah - definitely not the first time - this is a tricky thing. My current plan is to come up with a test case for it.

**Comment by gelisam** [comment]
Sodium was removed due to #44, closing.
