### ISSUE TITLE
The link to gloss in the README results in a 404

### ISSUE THREAD

**Issue by jbrownson** [gelisam/frp-zoo#46]
the link provided is `https://github.com/gelisam/frp-zoo/blob/master/gloss.ouroborus.net`

I'm guessing gloss was moved from the main repo to `https://github.com/gelisam/gloss`?

**Comment by gelisam** [comment]
How embarrassing! gloss did not move, I simply mistyped the URL and you're the first to notice, or at least the first to report the problem. Thanks!
